notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install python --version=3.8.3 --forcex86
        - pip install canaries
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      script: python test.py
    - os: windows
      language: sh
      before_install:
        - choco install python --version=3.8.3
        - pip install canaries
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      script: python test.py
    - os: linux
      language: python
      python: 3.8
      before_install: pip install canaries
      script: python test.py
    - os: osx
      language: generic
      before_cache:
        - brew cleanup
        - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
      cache:
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      before_install:
        - brew update
        - brew install ccache
        - brew install openssl readline
        - brew upgrade python@3.8
        - sudo -H python3.8 -m pip install -U pip
        - sudo -H python3.8 -m pip install canaries
      script: python3.8 test.py
