notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
    - os: linux
      language: python
      python: 3.8
    - os: osx
      language: generic
script:
  - wget https://raw.githubusercontent.com/reity/canaries/master/canaries/canaries.py
  - python test.py
