notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install python --version=3.8.3 --forcex86
        - python --version
    - os: windows
      language: sh
      before_install:
        - choco install python --version=3.8.3
        - python --version
    - os: linux
      language: python
      python: 3.8
    - os: osx
      language: generic
script:
  - wget https://raw.githubusercontent.com/reity/canaries/master/canaries/canaries.py
  - python test.py
